language: node_js
node_js:
  - 6.0
script:
  # run unit tests
  - npm test
  # make sure docs build
  - npm run docs
deploy:
  # deploy docs
  provider: surge
  project: _docs
  domain: zaphod.surge.sh
  skip_cleanup: true

