language: node_js
node_js:
  - 6.0
script:
  # tests & coverage
  - npm run cover
  # make sure docs build
  - npm run docs
deploy:
  # deploy docs
  provider: surge
  project: _docs
  domain: zaphod.surge.sh
  # we need _docs to deploy
  skip_cleanup: true

