language: node_js
node_js:
  - 6.0
script:
  - npm run cover
  - npm run docs
  - npm run report
deploy:
  # deploy docs
  provider: surge
  project: _docs
  domain: zaphod.surge.sh
  # we need _docs to deploy
  skip_cleanup: true

